//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaladorWebService.WebServiceServidor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServiceServidor/", ConfigurationName="WebServiceServidor.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld(string traz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string traz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUneg(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUneg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalUnegAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminaEntregaEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminaEntregaEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminaEntregaEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminaEntregaEnderecoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamilia(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamilia", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaGrupo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaGrupo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaGrupoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaCategoria(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaCategoriaAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoriaSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaCategoriaSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoriaSub", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaCategoriaSubAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuarioFuncao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUsuarioFuncao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuarioFuncao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalUsuarioFuncaoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFuncionario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFuncionario(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFuncionarioAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUsuario(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalUsuarioAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalTributacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalTributacao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalTributacao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalTributacaoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProduto(System.DateTime data, int inicio, int fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoAsync(System.DateTime data, int inicio, int fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenio(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoBarra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoBarra(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoBarra", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoBarraAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoTributacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoTributacao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoTributacao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoTributacaoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoUneg(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoUneg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoUnegAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueDia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoEstoqueDia(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueDia", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoEstoqueDiaAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoEstoqueLote(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueLote", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoEstoqueLoteAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEspecialidade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrmEspecialidade(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEspecialidade", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalCrmEspecialidadeAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrm(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalCrmAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrmEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalCrmEnderecoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoContar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoContar(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoContar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoContarAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCliente(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalClienteAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalClienteEnderecoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteTelefone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteTelefone(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteTelefone", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalClienteTelefoneAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFornecedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFornecedor(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFornecedor", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFornecedorAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalBanco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalBanco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalBanco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalBancoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroEvento(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroEventoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroPrazo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroPrazo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroPrazo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroPrazoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSub", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraSubAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroAdministradora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroAdministradora(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroAdministradora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroAdministradoraAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/TestSyncServidorTerminalFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestSyncServidorTerminalFinalizadora(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/TestSyncServidorTerminalFinalizadora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestSyncServidorTerminalFinalizadoraAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalIbptAx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalIbptAx(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalIbptAx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalIbptAxAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalNegocioParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalNegocioParametro(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalNegocioParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalNegocioParametroAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroMarkup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroMarkup(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroMarkup", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroMarkupAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroComissao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroComissao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroComissao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroComissaoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalAbcFarma(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarma", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalAbcFarmaAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarmaPeriodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalAbcFarmaPeriodo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarmaPeriodo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalAbcFarmaPeriodoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoPrincAtivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoPrincAtivo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoPrincAtivo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoPrincAtivoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteFiscal(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalClienteFiscalAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenioCliente(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioClienteAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoTipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoTipo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoTipoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoProduto(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoProdutoAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescConv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescConv(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescConv", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescConvAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescProd(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescProdAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioFinalizadoraSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenioFinalizadoraSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioFinalizadoraSub", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioFinalizadoraSubAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProdUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescProdUneg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProdUneg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescProdUnegAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVendUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescVendUneg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVendUneg", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescVendUnegAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraUn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraUn(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraUn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraUnAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSubUn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraSubUn(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSubUn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraSubUnAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescVend(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVend", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescVendAsync(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceIdentificaTerminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServiceIdentificaTerminal(string SerieHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceIdentificaTerminal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ServiceIdentificaTerminalAsync(string SerieHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceInserirTerminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceInserirTerminal(string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceInserirTerminal", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceInserirTerminalAsync(string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaEcf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdentificaEcf(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaEcf", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IdentificaEcfAsync(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaFinalizadoras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdentificaFinalizadoras(string ecf_numero_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaFinalizadoras", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IdentificaFinalizadorasAsync(string ecf_numero_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ContaMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ContaMaquina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ContaMaquina", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ContaMaquinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorDataDeimport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorDataDeimport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorDataDeimport", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorDataDeimportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrm(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCrmAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrmEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrmEndereco(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrmEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCrmEnderecoAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCliente(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorClienteAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteEndereco(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteEndereco", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorClienteEnderecoAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteTelefone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteTelefone(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteTelefone", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorClienteTelefoneAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteAnvisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteAnvisa(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteAnvisa", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorClienteAnvisaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteFiscal(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteFiscal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorClienteFiscalAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPacienteAnvisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPacienteAnvisa(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPacienteAnvisa", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorPacienteAnvisaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrediario(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCrediarioAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediarioFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrediarioFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediarioFinalizadora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCrediarioFinalizadoraAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorEcf(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcf", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorEcfAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcfDd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorEcfDd(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcfDd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorEcfDdAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorReducaoZ(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZ", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorReducaoZAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZItens", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorReducaoZItens(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZItens", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorReducaoZItensAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecarga", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorRecarga(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecarga", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorRecargaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecargaFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorRecargaFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecargaFinalizadora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorRecargaFinalizadoraAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPrivateLabel(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorPrivateLabelAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabelFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPrivateLabelFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabelFinalizadora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorPrivateLabelFinalizadoraAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckin(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCheckinAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckinItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckinItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckinItem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCheckinItemAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckout(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckout", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCheckoutAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckoutItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckoutItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckoutItem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorCheckoutItemAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAberturaCaixa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorAberturaCaixa(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAberturaCaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorAberturaCaixaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAgendaProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorAgendaProduto(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAgendaProduto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorAgendaProdutoAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorLanctoFinanceiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorLanctoFinanceiro(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorLanctoFinanceiro", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorLanctoFinanceiroAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfe(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorNfeAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeCfop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeCfop(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeCfop", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorNfeCfopAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeDanfe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeDanfe(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeDanfe", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorNfeDanfeAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeFinalizadora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorNfeFinalizadoraAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeItem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorNfeItemAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPonto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPonto(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPonto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorPontoAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSangria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorSangria(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSangria", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorSangriaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSuprimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorSuprimento(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSuprimento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorSuprimentoAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVenda(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorVendaAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVendaItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaItem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorVendaItemAsync(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVendaPagamento(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaPagamento", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SyncTerminalServidorVendaPagamentoAsync(string obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : InstaladorWebService.WebServiceServidor.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<InstaladorWebService.WebServiceServidor.Service1Soap>, InstaladorWebService.WebServiceServidor.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld(string traz) {
            return base.Channel.HelloWorld(traz);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string traz) {
            return base.Channel.HelloWorldAsync(traz);
        }
        
        public string SyncServidorTerminalUneg(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUneg(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalUnegAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUnegAsync(data);
        }
        
        public string SyncServidorTerminaEntregaEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminaEntregaEndereco(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminaEntregaEnderecoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminaEntregaEnderecoAsync(data);
        }
        
        public string SyncServidorTerminalProdutoFamilia(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamilia(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaAsync(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaGrupo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaGrupo(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaGrupoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaGrupoAsync(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaCategoria(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoria(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaCategoriaAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoriaAsync(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaCategoriaSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoriaSub(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoFamiliaCategoriaSubAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoriaSubAsync(data);
        }
        
        public string SyncServidorTerminalUsuarioFuncao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuarioFuncao(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalUsuarioFuncaoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuarioFuncaoAsync(data);
        }
        
        public string SyncServidorTerminalFuncionario(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFuncionario(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFuncionarioAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFuncionarioAsync(data);
        }
        
        public string SyncServidorTerminalUsuario(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuario(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalUsuarioAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuarioAsync(data);
        }
        
        public string SyncServidorTerminalTributacao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalTributacao(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalTributacaoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalTributacaoAsync(data);
        }
        
        public string SyncServidorTerminalProduto(System.DateTime data, int inicio, int fim) {
            return base.Channel.SyncServidorTerminalProduto(data, inicio, fim);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoAsync(System.DateTime data, int inicio, int fim) {
            return base.Channel.SyncServidorTerminalProdutoAsync(data, inicio, fim);
        }
        
        public string SyncServidorTerminalConvenio(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenio(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioAsync(data);
        }
        
        public string SyncServidorTerminalProdutoBarra(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoBarra(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoBarraAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoBarraAsync(data);
        }
        
        public string SyncServidorTerminalProdutoTributacao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoTributacao(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoTributacaoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoTributacaoAsync(data);
        }
        
        public string SyncServidorTerminalProdutoUneg(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoUneg(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoUnegAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoUnegAsync(data);
        }
        
        public string SyncServidorTerminalProdutoEstoqueDia(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueDia(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoEstoqueDiaAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueDiaAsync(data);
        }
        
        public string SyncServidorTerminalProdutoEstoqueLote(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueLote(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoEstoqueLoteAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueLoteAsync(data);
        }
        
        public string SyncServidorTerminalCrmEspecialidade(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEspecialidade(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalCrmEspecialidadeAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEspecialidadeAsync(data);
        }
        
        public string SyncServidorTerminalCrm(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrm(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalCrmAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmAsync(data);
        }
        
        public string SyncServidorTerminalCrmEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEndereco(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalCrmEnderecoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEnderecoAsync(data);
        }
        
        public string SyncServidorTerminalProdutoContar(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoContar(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoContarAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoContarAsync(data);
        }
        
        public string SyncServidorTerminalCliente(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCliente(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalClienteAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteAsync(data);
        }
        
        public string SyncServidorTerminalClienteEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteEndereco(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalClienteEnderecoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteEnderecoAsync(data);
        }
        
        public string SyncServidorTerminalClienteTelefone(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteTelefone(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalClienteTelefoneAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteTelefoneAsync(data);
        }
        
        public string SyncServidorTerminalFornecedor(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFornecedor(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFornecedorAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFornecedorAsync(data);
        }
        
        public string SyncServidorTerminalBanco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalBanco(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalBancoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalBancoAsync(data);
        }
        
        public string SyncServidorTerminalFinanceiroEvento(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroEvento(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroEventoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroEventoAsync(data);
        }
        
        public string SyncServidorTerminalFinanceiroPrazo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroPrazo(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroPrazoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroPrazoAsync(data);
        }
        
        public string SyncServidorTerminalFinalizadoraSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSub(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraSubAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSubAsync(data);
        }
        
        public string SyncServidorTerminalFinanceiroAdministradora(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroAdministradora(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinanceiroAdministradoraAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroAdministradoraAsync(data);
        }
        
        public string TestSyncServidorTerminalFinalizadora(System.DateTime data) {
            return base.Channel.TestSyncServidorTerminalFinalizadora(data);
        }
        
        public System.Threading.Tasks.Task<string> TestSyncServidorTerminalFinalizadoraAsync(System.DateTime data) {
            return base.Channel.TestSyncServidorTerminalFinalizadoraAsync(data);
        }
        
        public string SyncServidorTerminalIbptAx(System.DateTime data) {
            return base.Channel.SyncServidorTerminalIbptAx(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalIbptAxAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalIbptAxAsync(data);
        }
        
        public string SyncServidorTerminalNegocioParametro(System.DateTime data) {
            return base.Channel.SyncServidorTerminalNegocioParametro(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalNegocioParametroAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalNegocioParametroAsync(data);
        }
        
        public string SyncServidorTerminalParametroMarkup(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroMarkup(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroMarkupAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroMarkupAsync(data);
        }
        
        public string SyncServidorTerminalParametroComissao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroComissao(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroComissaoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroComissaoAsync(data);
        }
        
        public string SyncServidorTerminalAbcFarma(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarma(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalAbcFarmaAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarmaAsync(data);
        }
        
        public string SyncServidorTerminalAbcFarmaPeriodo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarmaPeriodo(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalAbcFarmaPeriodoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarmaPeriodoAsync(data);
        }
        
        public string SyncServidorTerminalProdutoPrincAtivo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoPrincAtivo(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalProdutoPrincAtivoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoPrincAtivoAsync(data);
        }
        
        public string SyncServidorTerminalClienteFiscal(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteFiscal(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalClienteFiscalAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteFiscalAsync(data);
        }
        
        public string SyncServidorTerminalConvenioCliente(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioCliente(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioClienteAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioClienteAsync(data);
        }
        
        public string SyncServidorTerminalPromocaoTipo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoTipo(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoTipoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoTipoAsync(data);
        }
        
        public string SyncServidorTerminalPromocao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocao(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoAsync(data);
        }
        
        public string SyncServidorTerminalPromocaoProduto(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoProduto(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalPromocaoProdutoAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoProdutoAsync(data);
        }
        
        public string SyncServidorTerminalParametroDescConv(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescConv(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescConvAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescConvAsync(data);
        }
        
        public string SyncServidorTerminalParametroDescProd(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescProd(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescProdAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescProdAsync(data);
        }
        
        public string SyncServidorTerminalConvenioFinalizadoraSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioFinalizadoraSub(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalConvenioFinalizadoraSubAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioFinalizadoraSubAsync(data);
        }
        
        public string SyncServidorTerminalParametroDescProdUneg() {
            return base.Channel.SyncServidorTerminalParametroDescProdUneg();
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescProdUnegAsync() {
            return base.Channel.SyncServidorTerminalParametroDescProdUnegAsync();
        }
        
        public string SyncServidorTerminalParametroDescVendUneg() {
            return base.Channel.SyncServidorTerminalParametroDescVendUneg();
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescVendUnegAsync() {
            return base.Channel.SyncServidorTerminalParametroDescVendUnegAsync();
        }
        
        public string SyncServidorTerminalFinalizadoraUn(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraUn(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraUnAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraUnAsync(data);
        }
        
        public string SyncServidorTerminalFinalizadoraSubUn(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSubUn(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalFinalizadoraSubUnAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSubUnAsync(data);
        }
        
        public string SyncServidorTerminalParametroDescVend(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescVend(data);
        }
        
        public System.Threading.Tasks.Task<string> SyncServidorTerminalParametroDescVendAsync(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescVendAsync(data);
        }
        
        public string ServiceIdentificaTerminal(string SerieHD) {
            return base.Channel.ServiceIdentificaTerminal(SerieHD);
        }
        
        public System.Threading.Tasks.Task<string> ServiceIdentificaTerminalAsync(string SerieHD) {
            return base.Channel.ServiceIdentificaTerminalAsync(SerieHD);
        }
        
        public bool ServiceInserirTerminal(string terminal) {
            return base.Channel.ServiceInserirTerminal(terminal);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceInserirTerminalAsync(string terminal) {
            return base.Channel.ServiceInserirTerminalAsync(terminal);
        }
        
        public string IdentificaEcf(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo) {
            return base.Channel.IdentificaEcf(ecfm_id_marca, ecfm_id_versao, ecfm_id_modelo);
        }
        
        public System.Threading.Tasks.Task<string> IdentificaEcfAsync(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo) {
            return base.Channel.IdentificaEcfAsync(ecfm_id_marca, ecfm_id_versao, ecfm_id_modelo);
        }
        
        public string IdentificaFinalizadoras(string ecf_numero_serie) {
            return base.Channel.IdentificaFinalizadoras(ecf_numero_serie);
        }
        
        public System.Threading.Tasks.Task<string> IdentificaFinalizadorasAsync(string ecf_numero_serie) {
            return base.Channel.IdentificaFinalizadorasAsync(ecf_numero_serie);
        }
        
        public string ContaMaquina() {
            return base.Channel.ContaMaquina();
        }
        
        public System.Threading.Tasks.Task<string> ContaMaquinaAsync() {
            return base.Channel.ContaMaquinaAsync();
        }
        
        public string SyncTerminalServidorDataDeimport() {
            return base.Channel.SyncTerminalServidorDataDeimport();
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorDataDeimportAsync() {
            return base.Channel.SyncTerminalServidorDataDeimportAsync();
        }
        
        public string SyncTerminalServidorCrm(string obj) {
            return base.Channel.SyncTerminalServidorCrm(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCrmAsync(string obj) {
            return base.Channel.SyncTerminalServidorCrmAsync(obj);
        }
        
        public string SyncTerminalServidorCrmEndereco(string obj) {
            return base.Channel.SyncTerminalServidorCrmEndereco(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCrmEnderecoAsync(string obj) {
            return base.Channel.SyncTerminalServidorCrmEnderecoAsync(obj);
        }
        
        public string SyncTerminalServidorCliente(string obj) {
            return base.Channel.SyncTerminalServidorCliente(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorClienteAsync(string obj) {
            return base.Channel.SyncTerminalServidorClienteAsync(obj);
        }
        
        public string SyncTerminalServidorClienteEndereco(string obj) {
            return base.Channel.SyncTerminalServidorClienteEndereco(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorClienteEnderecoAsync(string obj) {
            return base.Channel.SyncTerminalServidorClienteEnderecoAsync(obj);
        }
        
        public string SyncTerminalServidorClienteTelefone(string obj) {
            return base.Channel.SyncTerminalServidorClienteTelefone(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorClienteTelefoneAsync(string obj) {
            return base.Channel.SyncTerminalServidorClienteTelefoneAsync(obj);
        }
        
        public string SyncTerminalServidorClienteAnvisa(string obj) {
            return base.Channel.SyncTerminalServidorClienteAnvisa(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorClienteAnvisaAsync(string obj) {
            return base.Channel.SyncTerminalServidorClienteAnvisaAsync(obj);
        }
        
        public string SyncTerminalServidorClienteFiscal(string obj) {
            return base.Channel.SyncTerminalServidorClienteFiscal(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorClienteFiscalAsync(string obj) {
            return base.Channel.SyncTerminalServidorClienteFiscalAsync(obj);
        }
        
        public string SyncTerminalServidorPacienteAnvisa(string obj) {
            return base.Channel.SyncTerminalServidorPacienteAnvisa(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorPacienteAnvisaAsync(string obj) {
            return base.Channel.SyncTerminalServidorPacienteAnvisaAsync(obj);
        }
        
        public string SyncTerminalServidorCrediario(string obj) {
            return base.Channel.SyncTerminalServidorCrediario(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCrediarioAsync(string obj) {
            return base.Channel.SyncTerminalServidorCrediarioAsync(obj);
        }
        
        public string SyncTerminalServidorCrediarioFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorCrediarioFinalizadora(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCrediarioFinalizadoraAsync(string obj) {
            return base.Channel.SyncTerminalServidorCrediarioFinalizadoraAsync(obj);
        }
        
        public string SyncTerminalServidorEcf(string obj) {
            return base.Channel.SyncTerminalServidorEcf(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorEcfAsync(string obj) {
            return base.Channel.SyncTerminalServidorEcfAsync(obj);
        }
        
        public string SyncTerminalServidorEcfDd(string obj) {
            return base.Channel.SyncTerminalServidorEcfDd(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorEcfDdAsync(string obj) {
            return base.Channel.SyncTerminalServidorEcfDdAsync(obj);
        }
        
        public string SyncTerminalServidorReducaoZ(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZ(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorReducaoZAsync(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZAsync(obj);
        }
        
        public string SyncTerminalServidorReducaoZItens(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZItens(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorReducaoZItensAsync(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZItensAsync(obj);
        }
        
        public string SyncTerminalServidorRecarga(string obj) {
            return base.Channel.SyncTerminalServidorRecarga(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorRecargaAsync(string obj) {
            return base.Channel.SyncTerminalServidorRecargaAsync(obj);
        }
        
        public string SyncTerminalServidorRecargaFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorRecargaFinalizadora(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorRecargaFinalizadoraAsync(string obj) {
            return base.Channel.SyncTerminalServidorRecargaFinalizadoraAsync(obj);
        }
        
        public string SyncTerminalServidorPrivateLabel(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabel(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorPrivateLabelAsync(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabelAsync(obj);
        }
        
        public string SyncTerminalServidorPrivateLabelFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabelFinalizadora(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorPrivateLabelFinalizadoraAsync(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabelFinalizadoraAsync(obj);
        }
        
        public string SyncTerminalServidorCheckin(string obj) {
            return base.Channel.SyncTerminalServidorCheckin(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCheckinAsync(string obj) {
            return base.Channel.SyncTerminalServidorCheckinAsync(obj);
        }
        
        public string SyncTerminalServidorCheckinItem(string obj) {
            return base.Channel.SyncTerminalServidorCheckinItem(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCheckinItemAsync(string obj) {
            return base.Channel.SyncTerminalServidorCheckinItemAsync(obj);
        }
        
        public string SyncTerminalServidorCheckout(string obj) {
            return base.Channel.SyncTerminalServidorCheckout(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCheckoutAsync(string obj) {
            return base.Channel.SyncTerminalServidorCheckoutAsync(obj);
        }
        
        public string SyncTerminalServidorCheckoutItem(string obj) {
            return base.Channel.SyncTerminalServidorCheckoutItem(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorCheckoutItemAsync(string obj) {
            return base.Channel.SyncTerminalServidorCheckoutItemAsync(obj);
        }
        
        public string SyncTerminalServidorAberturaCaixa(string obj) {
            return base.Channel.SyncTerminalServidorAberturaCaixa(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorAberturaCaixaAsync(string obj) {
            return base.Channel.SyncTerminalServidorAberturaCaixaAsync(obj);
        }
        
        public string SyncTerminalServidorAgendaProduto(string obj) {
            return base.Channel.SyncTerminalServidorAgendaProduto(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorAgendaProdutoAsync(string obj) {
            return base.Channel.SyncTerminalServidorAgendaProdutoAsync(obj);
        }
        
        public string SyncTerminalServidorLanctoFinanceiro(string obj) {
            return base.Channel.SyncTerminalServidorLanctoFinanceiro(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorLanctoFinanceiroAsync(string obj) {
            return base.Channel.SyncTerminalServidorLanctoFinanceiroAsync(obj);
        }
        
        public string SyncTerminalServidorNfe(string obj) {
            return base.Channel.SyncTerminalServidorNfe(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorNfeAsync(string obj) {
            return base.Channel.SyncTerminalServidorNfeAsync(obj);
        }
        
        public string SyncTerminalServidorNfeCfop(string obj) {
            return base.Channel.SyncTerminalServidorNfeCfop(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorNfeCfopAsync(string obj) {
            return base.Channel.SyncTerminalServidorNfeCfopAsync(obj);
        }
        
        public string SyncTerminalServidorNfeDanfe(string obj) {
            return base.Channel.SyncTerminalServidorNfeDanfe(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorNfeDanfeAsync(string obj) {
            return base.Channel.SyncTerminalServidorNfeDanfeAsync(obj);
        }
        
        public string SyncTerminalServidorNfeFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorNfeFinalizadora(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorNfeFinalizadoraAsync(string obj) {
            return base.Channel.SyncTerminalServidorNfeFinalizadoraAsync(obj);
        }
        
        public string SyncTerminalServidorNfeItem(string obj) {
            return base.Channel.SyncTerminalServidorNfeItem(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorNfeItemAsync(string obj) {
            return base.Channel.SyncTerminalServidorNfeItemAsync(obj);
        }
        
        public string SyncTerminalServidorPonto(string obj) {
            return base.Channel.SyncTerminalServidorPonto(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorPontoAsync(string obj) {
            return base.Channel.SyncTerminalServidorPontoAsync(obj);
        }
        
        public string SyncTerminalServidorSangria(string obj) {
            return base.Channel.SyncTerminalServidorSangria(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorSangriaAsync(string obj) {
            return base.Channel.SyncTerminalServidorSangriaAsync(obj);
        }
        
        public string SyncTerminalServidorSuprimento(string obj) {
            return base.Channel.SyncTerminalServidorSuprimento(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorSuprimentoAsync(string obj) {
            return base.Channel.SyncTerminalServidorSuprimentoAsync(obj);
        }
        
        public string SyncTerminalServidorVenda(string obj) {
            return base.Channel.SyncTerminalServidorVenda(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorVendaAsync(string obj) {
            return base.Channel.SyncTerminalServidorVendaAsync(obj);
        }
        
        public string SyncTerminalServidorVendaItem(string obj) {
            return base.Channel.SyncTerminalServidorVendaItem(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorVendaItemAsync(string obj) {
            return base.Channel.SyncTerminalServidorVendaItemAsync(obj);
        }
        
        public string SyncTerminalServidorVendaPagamento(string obj) {
            return base.Channel.SyncTerminalServidorVendaPagamento(obj);
        }
        
        public System.Threading.Tasks.Task<string> SyncTerminalServidorVendaPagamentoAsync(string obj) {
            return base.Channel.SyncTerminalServidorVendaPagamentoAsync(obj);
        }
    }
}
